# Site settings
title: This and that
email: javier@okio.io
avatar: https://avatars3.githubusercontent.com/u/676181
description: > # this means to ignore newlines until "baseurl:"
  Random things that interest me and did not know where else to write them down. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jcard0na.github.io" # the base hostname & protocol for your site
twitter_username: jcard0na
github_username: jcard0na

# Build settings
markdown: kramdown
